### PR TITLE
Fix a few issues with getVolumePath

### PR DESCRIPTION
**Pull request by RobbWatershed**
Fix a few issues with getVolumePath
- Not working on API30 => use `getDirectory` instead of `getPath` / `getPathFile`
- GetUuid not available on API19-20 => raise minSDK to API21

### CODE REVIEW

**Comment by tom5079** [comment]
You are supposed to include idea folder in git

See: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

**Comment by RobbWatershed** [comment]
My bad, you just taught me something...

**Comment by tom5079** [comment]
Can you review commit 59f801f? I'm not sure if it's flawed or not...

**Comment by tom5079** [comment]
Do you prefer

```kotlin
context.contentResolver.query(
    childUri,
    arrayOf(
        DocumentsContract.Document.COLUMN_DOCUMENT_ID,
        DocumentsContract.Document.COLUMN_DISPLAY_NAME
    ),
    null,
    null,
    null
)
```

over

```kotlin
context.contentResolver.query(childUri, arrayOf(DocumentsContract.Document.COLUMN_DOCUMENT_ID, DocumentsContract.Document.COLUMN_DISPLAY_NAME), null, null, null)
```

?

How about

```kotlin
context.contentResolver.query(
    childUri,
    arrayOf(
        DocumentsContract.Document.COLUMN_DOCUMENT_ID,
        DocumentsContract.Document.COLUMN_DISPLAY_NAME
    ), null, null, null
)
```

**Comment by RobbWatershed** [comment]
3rd version looks like a good compromise

**Comment by tom5079** [comment]
> True. Is it the same when you autoformat on your Android Studio?

nope, I disabled autoformat. I don't believe in 80 column limit :joy:

**Comment by tom5079** [comment]
did you check 59f801f? Can't merge without your OK ;)

**Comment by RobbWatershed** [comment]
> did you check [59f801f](https://github.com/tom5079/DocumentFileX/commit/59f801fe8a627a7900d7be9fa6c34a925afadc32)? Can't merge without your OK ;)

Done 😄

**Comment by tom5079** [comment]
OK! Merged :)
Thanks for your contribution :heart:

**Pull request merged**
